name: Multi Environment Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        required: true
        type: choice
        options:
          - DEV
          - TEST
          - PRE-PROD
          - PROD

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Show selected environment
        run: |
          echo "Selected environment: ${{ inputs.environment }}"
